# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "on_the_map"
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Kristian Mandrup"]
  s.date = "2013-03-04"
  s.description = "Makes it easy to add functionality to models related to geocoding, addressing and placing them as pins on a map"
  s.email = "kmandrup@gmail.com"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.md"
  ]
  s.files = [
    ".document",
    ".rspec",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.md",
    "Rakefile",
    "VERSION",
    "lib/address.rb",
    "lib/on_the_map.rb",
    "lib/on_the_map/addressable.rb",
    "lib/on_the_map/geo_locatable.rb",
    "lib/on_the_map/mappable.rb",
    "lib/on_the_map/positionable.rb",
    "on_the_map.gemspec",
    "spec/address_spec.rb",
    "spec/on_the_map/addressable_spec.rb",
    "spec/on_the_map/geo_locatable_spec.rb",
    "spec/on_the_map/geo_locatable_valid_spec.rb",
    "spec/on_the_map/mappable_spec.rb",
    "spec/on_the_map/positionable_spec.rb",
    "spec/on_the_map_spec.rb",
    "spec/spec_helper.rb",
    "spec/support/gmaps_lookup_stubs.rb"
  ]
  s.homepage = "http://github.com/kristianmandrup/on_the_map"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.25"
  s.summary = "Pre-baked Mongoid concerns to put models on the map"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<mongoid>, [">= 4"])
      s.add_runtime_dependency(%q<sugar-high>, ["~> 0.7.3"])
      s.add_runtime_dependency(%q<hashie>, ["~> 1.2"])
      s.add_runtime_dependency(%q<concerned>, ["~> 0.1.3"])
      s.add_development_dependency(%q<rspec>, [">= 2.12.0"])
      s.add_development_dependency(%q<rdoc>, [">= 3.1"])
      s.add_development_dependency(%q<bundler>, [">= 1.1.0"])
      s.add_development_dependency(%q<jeweler>, [">= 1.8.4"])
      s.add_development_dependency(%q<simplecov>, [">= 0.5"])
    else
      s.add_dependency(%q<mongoid>, [">= 4"])
      s.add_dependency(%q<sugar-high>, ["~> 0.7.3"])
      s.add_dependency(%q<hashie>, ["~> 1.2"])
      s.add_dependency(%q<concerned>, ["~> 0.1.3"])
      s.add_dependency(%q<rspec>, [">= 2.12.0"])
      s.add_dependency(%q<rdoc>, [">= 3.1"])
      s.add_dependency(%q<bundler>, [">= 1.1.0"])
      s.add_dependency(%q<jeweler>, [">= 1.8.4"])
      s.add_dependency(%q<simplecov>, [">= 0.5"])
    end
  else
    s.add_dependency(%q<mongoid>, [">= 4"])
    s.add_dependency(%q<sugar-high>, ["~> 0.7.3"])
    s.add_dependency(%q<hashie>, ["~> 1.2"])
    s.add_dependency(%q<concerned>, ["~> 0.1.3"])
    s.add_dependency(%q<rspec>, [">= 2.12.0"])
    s.add_dependency(%q<rdoc>, [">= 3.1"])
    s.add_dependency(%q<bundler>, [">= 1.1.0"])
    s.add_dependency(%q<jeweler>, [">= 1.8.4"])
    s.add_dependency(%q<simplecov>, [">= 0.5"])
  end
end

